// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgreSqlPlayground.Database;

#nullable disable

namespace PostgreSqlPlayground.Database.Migrations
{
    [DbContext(typeof(PlaygroundContext))]
    partial class PlaygroundContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostgreSqlPlayground.Database.Entities.DeploymentHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("DeploymentHistory");
                });

            modelBuilder.Entity("PostgreSqlPlayground.Database.Entities.HistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SentAt");

                    b.HasIndex("Tenant", "EventType", "ResponseStatus", "SentAt");

                    b.ToTable("History");
                });

            modelBuilder.Entity("PostgreSqlPlayground.Database.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PostgreSqlPlayground.Database.Entities.SubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Tenant", "EventType");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("PostgreSqlPlayground.Database.Entities.DeploymentHistoryEntity", b =>
                {
                    b.HasOne("PostgreSqlPlayground.Database.Entities.ProjectEntity", "Project")
                        .WithMany("Deployments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PostgreSqlPlayground.Database.Entities.DeploymentSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("DeploymentHistoryEntityId");

                            b1.Property<Dictionary<string, string>>("EnvironmentVariables")
                                .IsRequired();

                            b1.Property<int>("Replicas");

                            b1.HasKey("DeploymentHistoryEntityId");

                            b1.ToTable("DeploymentHistory");

                            b1
                                .ToJson("Settings")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DeploymentHistoryEntityId");

                            b1.OwnsOne("PostgreSqlPlayground.Database.Entities.DatabaseSettings", "Database", b2 =>
                                {
                                    b2.Property<Guid>("DeploymentSettingsDeploymentHistoryEntityId");

                                    b2.Property<string>("DatabaseName")
                                        .IsRequired();

                                    b2.Property<int>("MaxConnections");

                                    b2.Property<string>("Provider")
                                        .IsRequired();

                                    b2.Property<string>("Version")
                                        .IsRequired();

                                    b2.HasKey("DeploymentSettingsDeploymentHistoryEntityId");

                                    b2.ToTable("DeploymentHistory");

                                    b2.WithOwner()
                                        .HasForeignKey("DeploymentSettingsDeploymentHistoryEntityId");
                                });

                            b1.OwnsOne("PostgreSqlPlayground.Database.Entities.KafkaSettings", "Kafka", b2 =>
                                {
                                    b2.Property<Guid>("DeploymentSettingsDeploymentHistoryEntityId");

                                    b2.Property<string>("BootstrapServers")
                                        .IsRequired();

                                    b2.Property<bool>("Enabled");

                                    b2.Property<bool>("IdempotentProducer");

                                    b2.Property<int>("Partitions");

                                    b2.Property<string>("Topic")
                                        .IsRequired();

                                    b2.HasKey("DeploymentSettingsDeploymentHistoryEntityId");

                                    b2.ToTable("DeploymentHistory");

                                    b2.WithOwner()
                                        .HasForeignKey("DeploymentSettingsDeploymentHistoryEntityId");
                                });

                            b1.OwnsOne("PostgreSqlPlayground.Database.Entities.ResourceSettings", "Resources", b2 =>
                                {
                                    b2.Property<Guid>("DeploymentSettingsDeploymentHistoryEntityId");

                                    b2.Property<string>("CpuLimit")
                                        .IsRequired();

                                    b2.Property<string>("CpuRequest")
                                        .IsRequired();

                                    b2.Property<string>("MemoryLimit")
                                        .IsRequired();

                                    b2.Property<string>("MemoryRequest")
                                        .IsRequired();

                                    b2.HasKey("DeploymentSettingsDeploymentHistoryEntityId");

                                    b2.ToTable("DeploymentHistory");

                                    b2.WithOwner()
                                        .HasForeignKey("DeploymentSettingsDeploymentHistoryEntityId");
                                });

                            b1.Navigation("Database")
                                .IsRequired();

                            b1.Navigation("Kafka")
                                .IsRequired();

                            b1.Navigation("Resources")
                                .IsRequired();
                        });

                    b.Navigation("Project");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("PostgreSqlPlayground.Database.Entities.ProjectEntity", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
